spring.application.name=handloomProject
server.port=2030
spring.datasource.url= jdbc:mysql://root:TRjpcwttRbgZNnJIWodFYpcoGyLfRqZU@autorack.proxy.rlwy.net:22863/railway
spring.datasource.username = root
spring.datasource.password = TRjpcwttRbgZNnJIWodFYpcoGyLfRqZU
spring.jpa.hibernate.ddl-auto=update


