spring.application.name=handloomProject
server.port=2030
spring.datasource.url= jdbc:mysql://localhost:3306/handloom
spring.datasource.username = root
spring.datasource.password = root
spring.jpa.hibernate.ddl-auto=update


